name: Build
on:
    push:
        paths:
            - npm-binaries/package.json
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                include:
                    - arch: amd64
                      os: windows
                    - arch: amd64
                      os: linux
                    - arch: amd64
                      os: darwin
                    - arch: arm64
                      os: linux
                    - arch: arm64
                      os: darwin
                    - arch: arm64
                      os: windows
                    - arch: 386
                      os: windows
                    - arch: 386
                      os: linux
                    - arch: arm
                      os: linux

        name: ${{ matrix.os }} ${{ matrix.arch }}
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.22"

            - name: Build go binary
              run: go build -ldflags="-s -w" -trimpath -o npm-binaries/${{matrix.os}}-${{matrix.arch}}/ ./cmd/graphql-codegen
              env:
                  GOOS: ${{ matrix.os }}
                  GOARCH: ${{ matrix.arch }}
                  CGO_ENABLED: 0

            - name: Build binary npm package
              run: node scripts/build.js ${{ matrix.os }} ${{ matrix.arch }}

            - name: Publish npm package
              run: cd npm-binaries/${{matrix.os}}-${{matrix.arch}} && npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    deps:
        name: Update binary versions
        runs-on: ubuntu-latest
        permissions:
            contents: write
        needs: [build]
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Build binary npm package
              run: node scripts/update-deps.js

            - name: Set user
              run: git config --global user.name "github-actions[bot]"

            - name: Set email
              run: git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Commit changes
              run: git commit -am "Version Binaries"

            - name: Push changes
              run: git push
